### ISSUE TITLE
Allow file to specify its options

### ISSUE THREAD

**Issue by ckoppelman** [wandernauta/yuml#10]
I suggest allowing .yuml files to have a shebang instead of requiring command-line options.  Perhaps some coordination can be done with @cluther at https://github.com/cluther/sublime-yuml

**Comment by wandernauta** [comment]
What use case would you have in mind for this? A shebang usually indicates runnable programs that can be interpreted. A yuml diagram is not really a runnable program, and `yuml` is not an interpreter.

**Comment by ckoppelman** [comment]
My use case is this:

In my repo, I have a `docs/` folder with documentation about my code.  This includes pngs, markdown, etc.  My goal is to create a subdirectory `assets/` where I store files like .yuml which generate the pngs in the parent directory.  In my build process (probably part of release), I'd like to process everything in my `docs/` folder.  This includes batch processing the .yuml files that have changed since last release.   In order to batch process this, I need to specify somewhere the parameters I use for that yuml diagram.  

As a side note, it turns out by virtue of being a *nix program, you _do_ support shebangs.... so i can close this.
