### ISSUE TITLE
Handling of spaces in output

### ISSUE THREAD

**Issue by tlongers** [wandernauta/yuml#13]
Thanks for creating this handy tool. I spotted an issue. Try:

`echo "[this this]-[that that] | yuml -o output.png`

This gives me:

![diagram](https://user-images.githubusercontent.com/2115933/34040775-2a988d70-e18d-11e7-86a1-aab408ec7c8a.png)

The expected behaviour would be for spaces to be printed and not substituted.

Running Python 3.6.1 on OSX.

**Comment by wandernauta** [comment]
Thanks for the detailed report! The issue should be fixed now.

**Comment by tlongers** [comment]
Confirming fix. Thanks! 👍
